import type { Metadata } from "next";
import { Toaster } from "sonner";

import "@repo/ui/globals.css";
import { Providers } from "../components/providers";
import { fontHeading, fontSans } from "../lib/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fontSans.variable} ${fontHeading.variable} font-sans antialiased`}
      >
        <Providers>
          {children}
          <Toaster position="bottom-left" />
        </Providers>
      </body>
    </html>
  );
}
